version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=notie
      - POSTGRES_PASSWORD=notiepass
      - POSTGRES_DB=notiedb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notie -d notiedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_USER=notie
      - DB_PASSWORD=notiepass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=notiedb

volumes:
  db:
    driver: local
