version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=notie
      - POSTGRES_PASSWORD=notiepass
      - POSTGRES_DB=notiedb
    ports:
      - "5432:5432"
    volumes:
      - db_dev:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notie -d notiedb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_dev:
    driver: local
