version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=notie
      - POSTGRES_PASSWORD=notiepass
      - POSTGRES_DB=notiedb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
